# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 397b4c500191fb22194cc893a077fe1ae72d880f320a760b3569e717e7db3b6fe9c1717a6f9259574ac20efd9635dd417fd18fc9c1719d3e4ccfc2d71a3f9ee4

test:
  secret_key_base: a7190ead77547f212dc0ebb0af507f4e026770b6bc4a45f55f5afc86f6acc2d74252d3647dacd2e43ac4d828080dca45a074202a3e3dfc297776f6209f63be9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
